FROM python:3.13-slim AS production

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

RUN pip install uv

COPY pyproject.toml uv.lock ./
RUN uv sync --no-dev

COPY src/ src/

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


FROM production AS test

RUN uv sync --all-groups

COPY tests/ tests/

CMD ["uv", "run", "pytest", "-v"]
