services:
  db:
    container_name: iris-db
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: iris-api
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./models:/app/models
    depends_on:
      - db

  train:
    container_name: iris-train
    build:
      context: .
      dockerfile: Dockerfile.train
    env_file:
      - .env
    volumes:
      - ./models:/app/models
    profiles:
      - train

volumes:
  postgres_data:
